export const translateBackendError = (message, lang) => {
  if (lang !== 'en' || !message) return message;
  
  const mapEn = {
    "Không thể điều chỉnh chỉ số cho hóa đơn đã thanh toán. Vui lòng hoàn tiền hoặc hủy thanh toán trước.": "Cannot adjust the index for a paid invoice. Please refund or cancel the payment first.",
    "Số tiền hoàn/giảm trừ không được vượt quá tổng tiền của hóa đơn.": "The refund/deduction amount cannot exceed the total invoice amount.",
    "Chỉ có thể chốt các vi phạm ở trạng thái Pending hoặc Notified mà chưa có kháng nghị.": "Only violations in Pending or Notified status without appeals can be finalized.",
    "Chỉ có thể xuất hóa đơn cho các vi phạm đã có quyết định cuối cùng (FinalApproved).": "Invoices can only be issued for violations with a final decision (FinalApproved).",
    "Biên bản này chưa có số tiền phạt hợp lệ để tạo hóa đơn.": "This record does not have a valid penalty amount to create an invoice.",
    "Không tìm thấy Loại phí cấu hình cho 'Tiền phạt' trong hệ thống. Vui lòng tạo Loại phí này trước.": "The fee type for 'Penalty' was not found in the system. Please create this fee type first.",
    "Bạn có hóa đơn quá hạn chưa thanh toán. Vui lòng hoàn tất công nợ trước khi đăng ký dịch vụ mới.": "You have an overdue unpaid invoice. Please clear your debt before registering for new services.",
    "Bạn không có quyền đăng ký dịch vụ cho sạp này.": "You do not have permission to register services for this stall.",
    "Dịch vụ này hiện không còn khả dụng. Vui lòng chọn dịch vụ khác.": "This service is currently unavailable. Please select another service.",
    "Dịch vụ này không được cung cấp tại chợ của sạp bạn đang thuê.": "This service is not provided at the market of the stall you are renting.",
    "Bạn đang có dịch vụ này đang hoạt động và chưa hoàn tất, không thể đăng ký thêm.": "You already have this service active and incomplete, cannot register again.",
    "Bạn đã đăng ký dịch vụ này rồi. Vui lòng kiểm tra lại trong phần Dịch vụ của tôi.": "You have already registered this service. Please check in the My Services section.",
    "Không tìm thấy thông tin đăng ký dịch vụ.": "Service registration information not found.",
    "Dịch vụ này đã được hủy.": "This service has been canceled.",
    "Đây là dịch vụ vận hành bắt buộc của chợ, không thể tự ý hủy. Vui lòng liên hệ Ban quản lý nếu có thắc mắc.": "This is a mandatory operation service of the market, cannot be canceled arbitrarily. Please contact Management if you have questions.",
    "Dịch vụ này đã được yêu cầu hủy gia hạn từ trước.": "This service has been requested to cancel renewal previously.",
    "Dịch vụ này đang được tự động gia hạn.": "This service is being auto-renewed.",
    "Chỉ có thể kích hoạt lại các dịch vụ đang chờ hủy gia hạn. Các dịch vụ đã hủy hoàn toàn vui lòng đăng ký mới.": "Only services pending renewal cancellation can be reactivated. For completely canceled services, please re-register.",
    "Tên loại phí này đã tồn tại trong hệ thống.": "This fee type name already exists in the system.",
    "Không thể sửa loại phí mặc định của hệ thống.": "Cannot edit the system's default fee type.",
    "Không thể xóa loại phí mặc định của hệ thống.": "Cannot delete the system's default fee type.",
    "Không thể xóa loại phí này vì hiện đang có dịch vụ hoạt động liên kết với nó.": "Cannot delete this fee type because an active service is linked to it.",
    "Không thể xóa loại phí này vì nó đang được liên kết với dữ liệu hóa đơn hoặc các dữ liệu khác trong hệ thống.": "Cannot delete this fee type because it is linked to invoice data or other data in the system.",
    "Tên dịch vụ này đã tồn tại và đang hoạt động trong hệ thống.": "This service name already exists and is active in the system.",
    "Bậc trước đó đã là vô cùng (null), không thể thêm bậc tiếp theo.": "The previous tier is already infinite (null), cannot add the next tier.",
    "Không tìm thấy dịch vụ.": "Service not found.",
    "Bạn không có quyền tạo hóa đơn cho sạp thuộc khu vực/chợ khác.": "You do not have permission to create invoices for stalls in another area/market.",
    "Bạn không có quyền xem chi tiết hóa đơn của chợ khác.": "You do not have permission to view invoice details of another market.",
    "Bạn không có quyền chỉnh sửa chỉ số điện/nước của sạp thuộc chợ khác.": "You do not have permission to edit electricity/water indices of stalls in another market.",
    "Bạn không có quyền duyệt thanh toán cho giao dịch của chợ khác.": "You do not have permission to approve payments for transactions of another market.",
    "Bạn không có quyền xem chi tiết công nợ của sạp thuộc chợ khác.": "You do not have permission to view debt details of stalls in another market.",
    "Bạn không có quyền trả lời đánh giá này vì sạp không thuộc quyền quản lý của bạn.": "You do not have permission to reply to this review because the stall is not under your management.",
    "Bạn không có quyền cập nhật loại phí chung của hệ thống.": "You do not have permission to update general system fee types.",
    "Bạn không có quyền cập nhật loại phí của chợ khác.": "You do not have permission to update fee types of another market.",
    "Bạn không có quyền xóa loại phí chung của hệ thống.": "You do not have permission to delete general system fee types.",
    "Bạn không có quyền xóa loại phí của chợ khác.": "You do not have permission to delete fee types of another market.",
    "Bạn không có quyền cập nhật dịch vụ của chợ khác.": "You do not have permission to update services of another market.",
    "Bạn không có quyền xóa dịch vụ của chợ khác.": "You do not have permission to delete services of another market.",
    "Bạn không có quyền xem đơn giá của chợ khác.": "You do not have permission to view prices of another market.",
    "Bạn không có quyền cập nhật đơn giá của chợ khác.": "You do not have permission to update prices of another market.",
    "Bạn không có quyền xóa đơn giá của chợ khác.": "You do not have permission to delete prices of another market.",
    "Bạn không có quyền chỉnh sửa đánh giá này.": "You do not have permission to edit this review.",
    "Không tìm thấy yêu cầu hoặc bạn không có quyền xem.": "Request not found or you do not have permission to view it.",
    "Bạn không có quyền tạo yêu cầu cho sạp này vì không có hợp đồng hợp lệ.": "You do not have permission to create requests for this stall because there is no valid contract.",
    "Không tìm thấy biên bản vi phạm hoặc bạn không có quyền kháng nghị biên bản này.": "Violation record not found or you do not have permission to appeal it.",
    "Không tìm thấy yêu cầu hoặc bạn không có quyền hủy.": "Request not found or you do not have permission to cancel it.",
    "Bạn không có quyền truy cập thông tin dịch vụ này.": "You do not have permission to access this service information."
  };

  return mapEn[message] || message;
};
