const fs = require('fs');
const path = require('path');

const viNew = require('./vi_new_errors_3.json');
const enNew = {
  "ERR_YEU_CAU_VOI_MA_ID_KHONG_TIM_THAY": "Request with code {{arg0}} not found.",
  "ERR_KHONG_TIM_THAY_KHANG_NGHI_VI_PHAM_VOI_MA_REQUESTID": "Violation appeal with code {{arg0}} not found.",
  "ERR_YEU_CAU_VOI_MA_REQUESTID_KHONG_TIM_THAY": "Request with code {{arg0}} not found.",
  "ERR_CHI_YEU_CAU_SUA_CHUA_FACILITYISSUE_MOI_CO_QUYET_DI": "Only FacilityIssue repair requests have quotation decisions.",
  "ERR_YEU_CAU_PHAI_O_TRANG_THAI_PENDINGMANAGERREVIEW_TRU": "The request must be in PendingManagerReview status before the Manager makes a decision.",
  "ERR_THE_REQUEST_DOES_NOT_HAVE_A_VALID_REPAIR_QUOTATION": "The request does not have a valid repair quotation awaiting review.",
  "ERR_THE_REQUEST_DOES_NOT_HAVE_A_VENDOR_WHO_CAN_CONFIRM": "The request does not have a vendor who can confirm the quotation.",
  "ERR_THE_MANAGER_ACCOUNT_IS_NOT_ASSIGNED_TO_A_MARKET": "The Manager account is not assigned to a market.",
  "ERR_ID_DANH_GIA_KHONG_HOP_LE": "Invalid review ID.",
  "ERR_NOI_DUNG_PHAN_HOI_KHONG_DUOC_DE_TRONG": "Response content must not be empty.",
  "ERR_KHONG_TIM_THAY_DANH_GIA": "Review not found.",
  "ERR_DANH_GIA_NAY_KHONG_THUOC_VE_SAP_NAO": "This review does not belong to any stall.",
  "ERR_BAN_KHONG_CO_QUYEN_TRA_LOI_DANH_GIA_NAY_VI_SAP_KHO": "You do not have permission to reply to this review because the stall is not under your management.",
  "ERR_BAN_DA_TRA_LOI_DANH_GIA_NAY_ROI_MOI_DANH_GIA_CHI_D": "You have already replied to this review. Each review can only be replied to once.",
  "ERR_INVOICE_WITH_ID_INVOICEID_NOT_FOUND": "Invoice with ID {{arg0}} not found.",
  "ERR_BAN_KHONG_CO_QUYEN_XEM_CHI_TIET_HOA_DON_CUA_CHO_KH": "You do not have permission to view invoice details of another market.",
  "ERR_INVOICE_WITH_ID_REQUEST_INVOICEID_NOT_FOUND": "Invoice with ID {{arg0}} not found.",
  "ERR_INVOICE_IS_IN_STATUS_INVOICE_STATUS_PAYMENT_CAN_ON": "Invoice is in status '{{arg0}}'. Payment can only be collected for 'Unpaid' invoices.",
  "ERR_HOA_DON_NAY_DA_DUOC_CAP_NHAT_BOI_MOT_NGUOI_KHAC_VU": "This invoice has been updated by someone else. Please reload the page.",
  "ERR_STALL_WITH_ID_STALLID_NOT_FOUND": "Stall with ID {{arg0}} not found.",
  "ERR_THE_STAFF_ACCOUNT_IS_NOT_ASSIGNED_TO_A_MARKET": "The staff account is not assigned to a market.",
  "ERR_ONLY_DRAFT_INVOICES_IN_THE_ACCOUNTANT_S_MARKET_CAN": "Only draft invoices in the accountant's market can be issued.",
  "ERR_KHONG_TIM_THAY_LOAI_PHI_ID_REQUEST_FEETYPEID": "Fee type ID {{arg0}} not found.",
  "ERR_KHONG_TIM_THAY_HOP_DONG_HOAT_DONG_CHO_GIAN_HANG_ID": "Operating contract for stall ID {{arg0}} not found.",
  "ERR_BAN_KHONG_CO_QUYEN_TAO_HOA_DON_CHO_SAP_THUOC_KHU_V": "You do not have permission to create invoices for stalls in other areas/markets.",
  "ERR_BAN_KHONG_CO_QUYEN_CHINH_SUA_CHI_SO_DIEN_NUOC_CUA": "You do not have permission to edit the electricity/water index of stalls in another market.",
  "ERR_DONG_HO_REQUEST_METERTYPE_CHUA_DUOC_CAI_DAT_CHO_SA": "The {{arg0}} meter has not been installed for this stall. A meter needs to be created first.",
  "ERR_KHONG_THE_DIEU_CHINH_CHI_SO_CHO_HOA_DON_DA_THANH_T": "Cannot adjust the index for a paid invoice. Please refund or cancel the payment first.",
  "ERR_KHONG_TIM_THAY_GIAO_DICH_ID_PAYMENTID": "Transaction ID {{arg0}} not found.",
  "ERR_KHONG_TIM_THAY_HOA_DON_LIEN_KET_VOI_GIAO_DICH_ID_P": "Invoice linked to transaction ID {{arg0}} not found.",
  "ERR_PAYMENT_IS_NO_LONGER_PENDING_VERIFICATION": "Payment is no longer pending verification.",
  "ERR_BAN_KHONG_CO_QUYEN_DUYET_THANH_TOAN_CHO_GIAO_DICH": "You do not have permission to approve payments for transactions in another market.",
  "ERR_DU_LIEU_NAY_DA_DUOC_CAP_NHAT_BOI_MOT_NGUOI_KHAC_VU": "This data has been updated by someone else. Please reload the page.",
  "ERR_KHONG_TIM_THAY_SAP_ID_STALLID": "Stall ID {{arg0}} not found.",
  "ERR_BAN_KHONG_CO_QUYEN_XEM_CHI_TIET_CONG_NO_CUA_SAP_TH": "You do not have permission to view debt details of stalls in another market.",
  "ERR_KHONG_TIM_THAY_SAP_HOAT_DONG_ID_REQUEST_STALLID_DE": "Active stall ID {{arg0}} not found to send debt reminder.",
  "ERR_KHONG_TIM_THAY_YEU_CAU_KHANG_NGHI_ID_REQUESTID": "Appeal request ID {{arg0}} not found.",
  "ERR_SO_TIEN_HOAN_GIAM_TRU_KHONG_DUOC_VUOT_QUA_TONG_TIE": "The refund/deduction amount cannot exceed the total invoice amount.",
  "ERR_KHANG_NGHI_NAY_DA_DUOC_CAP_NHAT_BOI_MOT_NGUOI_KHAC": "This appeal has been updated by someone else. Please reload the page.",
  "ERR_INVALID_BILLING_PERIOD": "Invalid billing period.",
  "ERR_ACCOUNTANT_ACCOUNT_WAS_NOT_FOUND": "Accountant account was not found.",
  "ERR_ID_SAP_KHONG_HOP_LE": "Invalid Stall ID.",
  "ERR_THANG_PHAI_NAM_TRONG_KHOANG_TU_1_DEN_12": "Month must be between 1 and 12.",
  "ERR_NAM_KHONG_HOP_LE_VUI_LONG_NHAP_TU_NAM_2000_DEN_SYS": "Invalid year. Please enter a year from 2000 to {{arg0}}.",
  "ERR_ID_CHO_KHONG_HOP_LE": "Invalid Market ID.",
  "ERR_DIEN_TICH_KHU_VUC_PHAI_LON_HON_0": "Area size must be greater than 0.",
  "ERR_TONG_DIEN_TICH_CAC_KHU_VUC_EXISTINGSIZE_AREA_SIZE": "The total size of the areas ({{arg0}} m²) exceeds the Market size ({{arg1}} m²).",
  "ERR_CHO_KHONG_TON_TAI_HOAC_DA_BI_XOA": "Market does not exist or has been deleted.",
  "ERR_KHONG_THE_THEM_KHU_VUC_VAO_CHO_DANG_O_TRANG_THAI_M": "Cannot add an area to a market in '{{arg0}}' status. Market must be Active.",
  "ERR_TEN_KHU_VUC_KHONG_DUOC_DE_TRONG": "Area name cannot be empty.",
  "ERR_TEN_KHU_VUC_NAY_DA_TON_TAI_TRONG_CHO_VUI_LONG_CHON": "This area name already exists in the market. Please choose another name.",
  "ERR_ID_KHU_VUC_KHONG_HOP_LE": "Invalid Area ID.",
  "ERR_KHU_VUC_KHONG_TON_TAI": "Area does not exist.",
  "ERR_CHO_CUA_KHU_VUC_NAY_KHONG_TON_TAI": "The market of this area does not exist.",
  "ERR_KHONG_THE_CHINH_SUA_KHU_VUC_THUOC_CHO_DANG_O_TRANG": "Cannot edit an area belonging to a market in '{{arg0}}' status. Market must be Active.",
  "ERR_KHONG_THE_THAY_DOI_NGANH_HANG_CUA_KHU_VUC_KHI_DA_C": "Cannot change the area's category when there are stalls inside.",
  "ERR_KHONG_THE_THAY_DOI_HINH_DANG_DIEN_TICH_KHU_VUC_KHI": "Cannot change the shape/size of the area when there are stalls inside.",
  "ERR_DIEN_TICH_KHU_VUC_REQUEST_SIZE_VALUE_F2_M_KHONG_DU": "Area size ({{arg0}} m²) cannot be smaller than the total size of existing stalls ({{arg1}} m²).",
  "ERR_KHONG_THE_XOA_KHU_VUC_THUOC_CHO_DANG_O_TRANG_THAI": "Cannot delete an area belonging to a market in '{{arg0}}' status. Market must be Active.",
  "ERR_KHONG_THE_XOA_KHU_VUC_VI_CO_SAP_DANG_CO_HOP_DONG_H": "Cannot delete the area because there are stalls with active contracts (rented).",
  "ERR_KHU_VUC_KHONG_TON_TAI_HOAC_DA_BI_XOA": "Area does not exist or has been deleted.",
  "ERR_SAP_KHONG_TON_TAI_HOAC_DA_BI_XOA": "Stall does not exist or has been deleted.",
  "ERR_DIEN_TICH_SAP_PHAI_LON_HON_0_M": "Stall area must be greater than 0 m².",
  "ERR_TONG_DIEN_TICH_CAC_SAP_EXISTINGSIZE_STALL_SIZE_VAL": "The total size of stalls ({{arg0}} m²) exceeds the Area size ({{arg1}} m²).",
  "ERR_KHONG_THE_THEM_SAP_VAO_KHU_VUC_THUOC_CHO_DANG_O_TR": "Cannot add a stall to an area belonging to a market in '{{arg0}}' status. Market must be Active.",
  "ERR_MA_SAP_NAY_DA_TON_TAI_TRONG_CHO_VUI_LONG_CHON_MA_K": "This stall code already exists in the market. Please choose another code.",
  "ERR_VUI_LONG_CHON_NGANH_HANG_CHO_KHU_VUC_TRUOC_KHI_THE": "Please select a Category for the Area before adding stalls to this area.",
  "ERR_MA_SAP_KHONG_DUOC_DE_TRONG": "Stall code cannot be empty.",
  "ERR_CHO_CUA_SAP_NAY_KHONG_TON_TAI": "The market for this stall does not exist.",
  "ERR_KHONG_THE_CHINH_SUA_SAP_THUOC_CHO_DANG_O_TRANG_THA": "Cannot edit a stall belonging to a market in '{{arg0}}' status. Market must be Active.",
  "ERR_KHU_VUC_CUA_SAP_NAY_CHUA_DUOC_CAU_HINH_NGANH_HANG": "The area of this stall does not have a configured Category. Please update the Category for the area first.",
  "ERR_STALL_WITH_ID_ID_NOT_FOUND": "Stall with id {{arg0}} not found.",
  "ERR_KHONG_THE_THAY_DOI_VI_TRI_SAP_THUOC_CHO_DANG_O_TRA": "Cannot change the position of a stall belonging to a market in '{{arg0}}' status. Market must be Active.",
  "ERR_TRANG_THAI_KHONG_DUOC_DE_TRONG": "Status cannot be empty.",
  "ERR_KHONG_THE_THAY_DOI_TRANG_THAI_SAP_THUOC_CHO_DANG_O": "Cannot change the status of a stall belonging to a market in '{{arg0}}' status. Market must be Active.",
  "ERR_SAP_DANG_CO_HOP_DONG_CHO_THUE_HIEU_LUC_TRANG_THAI": "The stall has an active lease contract, status must be 'Rented'.",
  "ERR_KHONG_THE_XOA_SAP_THUOC_CHO_DANG_O_TRANG_THAI_STAL": "Cannot delete a stall belonging to a market in '{{arg0}}' status. Market must be Active.",
  "ERR_KHONG_THE_XOA_SAP_VI_SAP_DANG_CO_HOP_DONG_HIEU_LUC": "Cannot delete the stall because it has an active contract (rented).",
  "ERR_ID_NGUOI_DUNG_KHONG_HOP_LE": "Invalid user ID.",
  "ERR_KHONG_TIM_THAY_NGUOI_DUNG_CO_ID_ID": "User with ID {{arg0}} not found.",
  "ERR_TAI_KHOAN_QUAN_LY_CHUA_SO_HUU_CHO_NAO_DUOC_PHE_DUY": "Manager account does not own any approved market.",
  "ERR_VAI_TRO_DUOC_CHON_KHONG_TON_TAI": "Selected role does not exist.",
  "ERR_EMAIL_NAY_DA_DUOC_SU_DUNG": "This email has already been used.",
  "ERR_SO_DIEN_THOAI_NAY_DA_DUOC_SU_DUNG": "This phone number has already been used.",
  "ERR_SO_CCCD_NAY_DA_DUOC_SU_DUNG": "This citizen ID number has already been used.",
  "ERR_EMAIL_NAY_DA_DUOC_SU_DUNG_BOI_NGUOI_DUNG_KHAC": "This email has already been used by another user.",
  "ERR_SO_DIEN_THOAI_NAY_DA_DUOC_SU_DUNG_BOI_NGUOI_DUNG_K": "This phone number has already been used by another user.",
  "ERR_SO_CCCD_NAY_DA_DUOC_SU_DUNG_BOI_NGUOI_DUNG_KHAC": "This citizen ID number has already been used by another user.",
  "ERR_DU_LIEU_KHONG_HOP_LE": "Invalid data.",
  "ERR_KHONG_TIM_THAY_NGUOI_DUNG": "User not found.",
  "ERR_SO_DIEN_THOAI_DA_DUOC_SU_DUNG_BOI_TAI_KHOAN_KHAC": "Phone number has already been used by another account.",
  "ERR_TRANG_THAI_KHONG_HOP_LE_PHAI_LA_ACTIVE_LOCKED_HOAC": "Invalid status. Must be Active, Locked, or Suspended.",
  "ERR_MAT_KHAU_MOI_PHAI_CO_IT_NHAT_6_KY_TU": "New password must have at least 6 characters.",
  "ERR_MAT_KHAU_XAC_NHAN_KHONG_KHOP": "Confirmation password does not match.",
  "ERR_MAT_KHAU_HIEN_TAI_KHONG_CHINH_XAC": "Current password is incorrect.",
  "ERR_MAT_KHAU_MOI_KHONG_DUOC_TRUNG_VOI_MAT_KHAU_HIEN_TA": "New password must not be the same as the current password.",
  "ERR_KHONG_TIM_THAY_TAI_KHOAN_NGUOI_DUNG_ID_USERID": "User account ID {{arg0}} not found.",
  "ERR_EMAIL_REQUEST_EMAIL_DA_DUOC_SU_DUNG_BOI_TAI_KHOAN": "Email '{{arg0}}' has already been used by another account.",
  "ERR_YEU_CAU_DANG_NHAP_KHONG_DUOC_DE_TRONG": "Login request cannot be empty.",
  "ERR_EMAIL_HOAC_MAT_KHAU_KHONG_CHINH_XAC": "Incorrect email or password.",
  "ERR_TAI_KHOAN_CUA_BAN_DANG_NGUNG_HOAT_DONG_INACTIVE_VU": "Your account is currently inactive. Please contact the Market Management Board via hotline 1900-8888 or email support@stmm.com for assistance.",
  "ERR_TAI_KHOAN_CHUA_DUOC_XAC_THUC_EMAIL_VUI_LONG_XAC_TH": "Account has not been email verified. Please verify before logging in.",
  "ERR_TAI_KHOAN_DA_BI_KHOA_HOAC_TAM_DUNG_VUI_LONG_LIEN_H": "Account has been locked or suspended. Please contact the Market Management Board for assistance.",
  "ERR_EMAIL_DA_DUOC_SU_DUNG": "Email has already been used.",
  "ERR_SO_DIEN_THOAI_DA_DUOC_SU_DUNG": "Phone number has already been used.",
  "ERR_CCCD_DA_DUOC_SU_DUNG": "Citizen ID has already been used.",
  "ERR_MA_XAC_THUC_DA_HET_HAN_HOAC_THONG_TIN_DANG_KY_KHON": "Verification code has expired or registration information is no longer valid. Please register again.",
  "ERR_MA_XAC_THUC_KHONG_CHINH_XAC": "Verification code is incorrect.",
  "ERR_MA_XAC_THUC_DA_HET_HAN_VUI_LONG_GUI_LAI_MA_MOI": "Verification code has expired. Please send a new code.",
  "ERR_EMAIL_DA_DUOC_DANG_KY_VA_XAC_THUC_BOI_TAI_KHOAN_KH": "Email has been registered and verified by another account.",
  "ERR_SO_DIEN_THOAI_DA_DUOC_DANG_KY_BOI_TAI_KHOAN_KHAC": "Phone number has been registered by another account.",
  "ERR_CCCD_DA_DUOC_DANG_KY_BOI_TAI_KHOAN_KHAC": "Citizen ID has been registered by another account.",
  "ERR_PHIEN_DANG_KY_KHONG_TON_TAI_HOAC_DA_HET_HAN_VUI_LO": "Registration session does not exist or has expired. Please register again.",
  "ERR_EMAIL_KHONG_TON_TAI_TRONG_HE_THONG": "Email does not exist in the system.",
  "ERR_TAI_KHOAN_DA_BI_KHOA_HOAC_TAM_DUNG": "Account has been locked or suspended.",
  "ERR_TAI_KHOAN_KHONG_TON_TAI": "Account does not exist.",
  "ERR_MA_XAC_THUC_DA_HET_HAN_VUI_LONG_YEU_CAU_MA_MOI": "Verification code has expired. Please request a new code.",
  "ERR_TOKEN_KHONG_HOP_LE": "Invalid token.",
  "ERR_TAI_KHOAN_KHONG_HOP_LE": "Invalid account.",
  "ERR_REFRESH_TOKEN_KHONG_HOP_LE": "Invalid refresh token.",
  "ERR_TOKEN_GOOGLE_KHONG_HOP_LE": "Invalid Google token.",
  "ERR_XAC_THUC_TOKEN_GOOGLE_THAT_BAI": "Google token verification failed.",
  "ERR_KHONG_THE_KET_NOI_TOI_GOOGLE_AUTH_API": "Cannot connect to Google Auth API.",
  "ERR_XAC_THUC_TOKEN_GOOGLE_THAT_BAI_HOAC_EMAIL_KHONG_HO": "Google token verification failed or email is invalid.",
  "ERR_MAT_KHAU_CU_KHONG_CHINH_XAC": "Old password is incorrect.",
  "ERR_NOTIFICATION_CANNOT_BE_SENT_TO_BOTH_A_SPECIFIC_USE": "Notification cannot be sent to both a specific user and a role simultaneously. Choose one of them.",
  "ERR_NOTIFICATION_MUST_HAVE_AT_LEAST_TARGETUSERID_OR_TA": "Notification must have at least TargetUserId or TargetRole.",
  "ERR_NO_ACTIVE_NOTIFICATION_RECIPIENT_WAS_FOUND": "No active notification recipient was found.",
  "ERR_NOTIFICATION_WITH_ID_NOTIID_NOT_FOUND": "Notification with ID {{arg0}} not found.",
  "ERR_DU_LIEU_DAU_VAO_KHONG_HOP_LE": "Invalid input data.",
  "ERR_MARKET_MAP_NOT_FOUND": "Market map not found.",
  "ERR_KHONG_TIM_THAY_CHO": "Market not found.",
  "ERR_CHO_NAY_DA_O_TRANG_THAI_NGUNG_HOAT_DONG_ROI": "This market is already inactive.",
  "ERR_CHO_DANG_CHO_DUYET_VUI_LONG_HUY_DANG_KY_THAY_VI_NG": "Market is awaiting approval. Please cancel registration instead of deactivating.",
  "ERR_BAN_KHONG_CO_QUYEN_NGUNG_HOAT_DONG_CHO_NAY": "You do not have permission to deactivate this market.",
  "ERR_MARKET_DEACTIVATE_ACTIVE_CONTRACTS_ACTIVECONTRACTC": "MARKET_DEACTIVATE_ACTIVE_CONTRACTS|{{arg0}}",
  "ERR_MARKET_DEACTIVATE_UNPAID_INVOICES_UNPAIDINVOICECOU": "MARKET_DEACTIVATE_UNPAID_INVOICES|{{arg0}}",
  "ERR_MARKET_DEACTIVATE_ACTIVE_SERVICES_ACTIVESERVICECOU": "MARKET_DEACTIVATE_ACTIVE_SERVICES|{{arg0}}"
};

const viPath = path.resolve(__dirname, '../stmm-client/src/locales/vi.json');
const enPath = path.resolve(__dirname, '../stmm-client/src/locales/en.json');
const viData = JSON.parse(fs.readFileSync(viPath, 'utf8'));
const enData = JSON.parse(fs.readFileSync(enPath, 'utf8'));

viData.errors = { ...viData.errors, ...viNew };
enData.errors = { ...enData.errors, ...enNew };

fs.writeFileSync(viPath, JSON.stringify(viData, null, 2));
fs.writeFileSync(enPath, JSON.stringify(enData, null, 2));
console.log('Merged successfully 3');
